[package]
name = "ledger-cli-personal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
distance = "0.4.0"
ledger-parser = "5.1.1"
